---
## Author
author:
  name: Мургия Марк Максимович
  degrees: DSc
  orcid: 0009-0006-9370-0808
  email: 1132243817@rudn.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      postal-code: 117198
      city: Москва
      address: ул. Миклухо-Маклая, д. 6

## Title
title: "Отчет Лабораторной работы №7"
subtitle: "Анализ файловой системы Linux. Команды для работы с файлами и каталогами"
license: "CC BY"
---

# Цель работы

Ознакомление с файловой системой Linux, её структурой, именами и содержанием каталогов. Приобретение практических навыков по применению команд для работы с файлами и каталогами, по управлению процессами (и работами), по проверке использования диска и обслуживанию файловой системы.

# Задание

1. Узнать функции команд cat, less, cp, mv и т.д.
2. Воспользоваться ими в Лабораторной работе

# Теоретическое введение

cat - для просмотра файлов небольшого размера

less - для просмотра файлов постранично

cp - копирует файлы

mv - двигает файлы

chmod - меняет права доступа

# Выполнение лабораторной работы

Нужно выполнить следующие действия:

1. cp /usr/include/sys/io.h equipment
2. mkdir ski.plases
3. mv equipment ski.plases
4. mv ~/ski.plases/equipment ~/ski.plases/equiplist
5. cp abc1 equiplist2
6. mv equiplist2 ski.plases
7. mkdir ~/skiplases/equipment
8. mv ~/ski.plases/equiplist ~/ski.plases/equiplist2 ~/ski.plases/equipment
9. mv newdir ~/ski.plases/plans

Далее нужно создать каталоги australia, play и файлы my_os, feathers. Используем команду chmod с этими файлами. На последок выполним следующие команды:

1. less passwd
2. cp feathers ~/file.old
3. mv ~/file.old ~/play
4. cp -r ~/play ~/fun
5. mv ~/fun ~/play/games
6. chmod u-r feathers
7. cat feathers (Permission denied)
8. cp feathers ... (Permission denied)
9. chmod u+r feathers
10. chmod u-x ~/play
11. cd play (Permission denied)
12. chmod u+x ~/play

Воспользуемся man с данными командами:

1. mount - mount a filesystem
2. fsck - check and repair a Linux file system
3. mkfs - build a Linux filesystem
4. kill - terminate a process



# Контрольные вопросы

1. Файловые системы (ФС) в Linux обеспечивают иерархическую структуру («дерево», начиная с /), поддерживая журналирование, права доступа и различные типы файлов (блочные, символьные, ссылки).
2. Файловая система Linux/Unix имеет древовидную иерархическую структуру, начинающуюся с корневого каталога
3. Чтобы содержимое файловой системы стало доступно в Linux, должна быть выполнена операция монтирования (mount). Она подключает файловую систему устройства (раздела диска, флешки) к общему дереву каталогов ОС, делая данные доступными по определенному пути (точке монтирования).
4. Основные причины нарушения целостности файловой системы Linux включают внезапное отключение питания, принудительную перезагрузку, аппаратные сбои накопителей (HDD/SSD) и ошибки записи, особенно при использовании NFS. Также к повреждениям ведут сбои в работе программного обеспечения, ошибки ядра и некорректное извлечение съемных носителей, прерывающее фиксацию данных. Устранение повреждений файловой системы Linux чаще всего выполняется с помощью утилиты fsck (File System Consistency Check).
5. Создание файловой системы в Linux включает выбор раздела диска (например, /dev/sdb1 с помощью fdisk или parted), его форматирование утилитой mkfs с указанием типа (ext4, XFS, Btrfs) и последующее монтирование в каталог для доступа к данным. Она организована в виде иерархического дерева, начинающегося с корневой директории /.
6. cat - для просмотра файлов небольшого размера; less - для просмотра файлов постранично; head - выводит по умолчанию первые 10 строк файла; tail - выводит умолчанию 10 последних строк файла
7. Команда cp (copy) в Linux предназначена для копирования файлов и директорий, сохраняя оригинал. Основные возможности включают создание копий файлов, рекурсивное копирование папок (-r), сохранение атрибутов (-p), интерактивное подтверждение перезаписи (-i) и копирование только новых файлов (-u).
8. Команда mv (move) в Linux предназначена для перемещения и переименования файлов и каталогов. Основные возможности включают изменение имени файла/папки, перенос их между директориями, а также принудительную или безопасную перезапись существующих файлов, работая как с одиночными файлами, так и с группами с использованием масок.
9. Права доступа являются характеристиками файла которые дают права на чтение, запись и выполнение. Меняются через команду chmod.

# Выводы

Мы ознакомились с файловой системой Linux, её структурой, именами и содержанием каталогов и приобрели практические навыки по применению команд для работы с файлами и каталогами, по управлению процессами (и работами), по проверке использования диска и обслуживанию файловой системы.

# Список литературы{.unnumbered}

::: {#refs}
:::
