---
## Author
author:
  name: Мургия Марк Максимович
  degrees: DSc
  orcid: 0009-0006-9370-0808
  email: 1132243817@rudn.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      postal-code: 117198
      city: Москва
      address: ул. Миклухо-Маклая, д. 6

## Title
title: "Отчет Лабораторной работы №8"
subtitle: "Поиск файлов. Перенаправление ввода-вывода. Просмотр запущенных процессов"
license: "CC BY"
---

# Цель работы

Ознакомление с инструментами поиска файлов и фильтрации текстовых данных. Приобретение практических навыков: по управлению процессами (и заданиями), по проверке использования диска и обслуживанию файловых систем.

# Задание

1. Ознакомиться с командами find, grep, df, du, gedit, ps
2. Сделать лабораторную работу

# Теоретическое введение

Команда find используется для поиска и отображения на экран имён файлов, соответствующих заданной строке символов.

Найти в текстовом файле указанную строку символов позволяет команда grep.

Команда df показывает размер каждого смонтированного раздела диска.

# Выполнение лабораторной работы

С помощью ">" нужно записать в файл file.txt названия файлов, содержащихся в каталоге /etc. Выведим имена всех файлов из file.txt, имеющих расширение .conf, после чего запишем их в новый текстовой файл conf.txt

Запустим в фоновом режиме процесс, который будет записывать в файл ~/logfile файлы, имена которых начинаются с log, потом удалим файл ~/logfile.

Запустим из консоли в фоновом режиме редактор gedit, определим идентификатор процесса gedit, используя команду ps, конвейер и фильтр grep, воспользуемся kill для завершения процесса gedit.

# Контрольные вопросы

1. stdin – ввод; stdout – вывод; stderr – вывод ошибки
2. При >: перенаправление вывода (stdout) в файл "filename". При >>: Перенаправление вывода (stdout) в файл "filename", файл открывается в режиме добавления.
3. Конвейер (pipe) служит для объединения простых команд или утилит в цепочки, в которых результат работы предыдущей команды передаётся последующей.
4. Процесс – последствие программы.
5. Process ID, Group ID
6. Запущенные фоном программы называются задачами (jobs). Ими можно управлять с помощью команды jobs, которая выводит список запущенных в данный момент задач.
7. Оба показывают нагрузку процессов.
8. Команда find используется для поиска и отображения на экран имён файлов, соответствующих заданной строке символов.
9. Найти в текстовом файле указанную строку символов позволяет команда grep
10. df -h
11. Команда du показывает число килобайт, используемое каждым файлом или каталогом.
12. Для завершения задачи необходимо выполнить команду kill.

# Выводы

Мы ознакомились с инструментами поиска файлов и фильтрации текстовых данных и приобрели практические навыки: по управлению процессами (и заданиями), по проверке использования диска и обслуживанию файловых систем.

# Список литературы{.unnumbered}

::: {#refs}
:::
